-- Weekly schedule generation now assigns a (possibly different) person to
-- each workstation for EACH work day (Mon-Fri), not one person for the
-- whole week. Add the day dimension to assignments and update uniqueness
-- to match: a person can now hold different stations on different days of
-- the same week, but still only one station per specific day.

alter table public.assignments add column if not exists assignment_date date;

-- Backfill: existing rows predate daily assignment — treat them as if they
-- applied to the week's Monday (the closest honest reading of old data).
-- Any week that actually needs true daily variety gets regenerated by the
-- Team Leader.
update public.assignments a
set assignment_date = sw.week_start_date
from public.schedule_weeks sw
where a.schedule_week_id = sw.id and a.assignment_date is null;

alter table public.assignments alter column assignment_date set not null;

alter table public.assignments
  drop constraint if exists assignments_schedule_week_id_associate_id_key;
alter table public.assignments
  add constraint assignments_schedule_week_id_associate_id_assignment_date_key
  unique (schedule_week_id, associate_id, assignment_date);

create index if not exists assignments_week_date_idx
  on public.assignments (schedule_week_id, assignment_date);
